name: pertypeople
version: 1.2.2+3
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  adobe_xd: ^2.0.1
  flutter_otp_text_field: ^1.0.1
  paytm_allinonesdk: ^1.2.1
  chip_list: ^2.4.3+8
  firebase_core:
  google_sign_in: ^5.3.3
  flutter_facebook_auth: ^5.0.7
  http: ^0.13.4
  otp_text_field: ^1.1.3
  image_cropper: ^2.0.3
  intl: ^0.17.0
  get_storage: ^2.0.3
  group_button: ^5.0.1
  google_maps_flutter: ^2.2.4
  image_picker: ^0.8.5+3
  geolocator: ^9.0.0
  geocoding: ^2.0.5
  google_place: ^0.4.7
  provider: ^6.0.3
  smooth_star_rating_null_safety: ^1.0.4+2
  razorpay_flutter: ^1.3.4
  fluttertoast: ^8.2.1
  flutter_stripe: ^5.0.0
  flutter_dotenv: ^5.0.2
  geocoder2: ^1.1.2
  image_crop: ^0.4.0
  custom_searchable_dropdown: ^2.1.1
  share_plus: ^6.3.0
  url_launcher: ^6.1.5
  google_fonts: ^4.0.3
  firebase_auth: ^4.2.4
  dots_indicator: ^2.1.0
  rflutter_alert: ^2.0.4
  paytm: ^3.0.1
  settings_ui: ^2.0.2
  showcaseview: ^2.0.1
  file_picker: ^5.2.5
  timer_count_down: ^2.2.0
  booking_calendar: ^1.1.9

  flutter_launcher_icons: ^0.11.0
  dio: ^5.0.0
  carousel_slider: ^4.2.1
  location: ^4.4.0
  quantity_input: ^1.0.2
  input_quantity: ^1.1.4
  flutter_multi_select_items: ^0.4.2
  custom_refresh_indicator: ^2.0.1
  dotted_line: ^3.1.0
  lottie: ^2.3.0
  firebase_storage: any
  cached_network_image: ^3.2.3
  responsive_grid_list: ^1.3.1

dev_dependencies:
  flutter_lints: ^2.0.0
  lints: ^2.0.1
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/dancecouple.png"




flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/
    - assets/dancecouple.png
    - assets/default_party_images/


  fonts:
    - family: SegeoUI
      fonts:
        - asset: assets/fonts/SEGOEUI.TTF

    - family: malgun
      fonts:
        - asset: assets/fonts/malgun.ttf

