// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgKs-IOOgtDmnC_BKf7Oj8U7yxOYFyX4Q',
    appId: '1:1080765497603:web:d35037930bc3831180a936',
    messagingSenderId: '1080765497603',
    projectId: 'pertypeople-53f50',
    authDomain: 'pertypeople-53f50.firebaseapp.com',
    storageBucket: 'pertypeople-53f50.appspot.com',
    measurementId: 'G-4BNRT6RXTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbMBbW0B4gIePXB3Y4FovCuuZ8tzN0C-M',
    appId: '1:1080765497603:android:17ce50a8a204669680a936',
    messagingSenderId: '1080765497603',
    projectId: 'pertypeople-53f50',
    storageBucket: 'pertypeople-53f50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXLt16AiTfx3fX56-8haB5KUa7062KRLE',
    appId: '1:1080765497603:ios:1f639bad2bc4f33f80a936',
    messagingSenderId: '1080765497603',
    projectId: 'pertypeople-53f50',
    storageBucket: 'pertypeople-53f50.appspot.com',
    androidClientId: '1080765497603-c1ebptad0b6s62oneuonqauasavk2u08.apps.googleusercontent.com',
    iosClientId: '1080765497603-qpsq2815nnjamuvaprbvj3vv7i07kv01.apps.googleusercontent.com',
    iosBundleId: 'coom.perty.pertypeople',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXLt16AiTfx3fX56-8haB5KUa7062KRLE',
    appId: '1:1080765497603:ios:1f639bad2bc4f33f80a936',
    messagingSenderId: '1080765497603',
    projectId: 'pertypeople-53f50',
    storageBucket: 'pertypeople-53f50.appspot.com',
    androidClientId: '1080765497603-c1ebptad0b6s62oneuonqauasavk2u08.apps.googleusercontent.com',
    iosClientId: '1080765497603-qpsq2815nnjamuvaprbvj3vv7i07kv01.apps.googleusercontent.com',
    iosBundleId: 'coom.perty.pertypeople',
  );
}
